require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  UseCache: true
  Exclude:
    - Gemfile
    - Gemfile.lock
    - spec/spec_helper.rb
Layout/LineLength:
  Max: 140
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
RSpec/DescribeClass:
  Exclude:
    - spec/**/*.rb
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/**/*.rb
